project_name: PatchSetsRL
experiment_name: Default

debug: False
gpu: 0

hparams:
  done_prob: 0.99
  total_steps_entropy_coef: 0.5
  start_entropy_coef: 1e-1
  end_entropy_coef: 1e-2

env_model:
  checkpoint_path: /workspace/src/epoch=1062.ckpt
  patch_size: 25
  hidden_n: 64
  feature_n: 64
  output_n: 26
  pool_mode: max
  seed: 0
  batch_size: 64
  num_workers: ~
  max_epochs: ~
  min_epochs: ~
  patience: ~
  optimizer: Adam
  lr: 1e-3

agent:
  gpu: ${gpu}
  gamma: 0.9
  update_interval: 1024
  minibatch_size: 64

experiment:
  steps: 100_000
  eval_interval: ${agent.update_interval}
  eval_n_episodes: 104
  eval_n_steps: ~
  train_max_episode_len: 8
  eval_max_episode_len: 8
  use_tensorboard: True

optim:
  lr: 1e-3
  eps: 1e-8

hydra:
  run:
    dir: ./outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
