project_name: charsk74k_recognition
experiment_name: Default

debug: False
gpu: ${oc.decode:${oc.env:GPU}}
dataset_name: Chars74kImageDataset

seed: 0

lightning_module:
  model_name: resnet18
  pretrained: False
  num_classes: 10
  lr: 0.001

data_module:
  batch_size: 64
  num_workers: 0
  pin_memory: False
  path: '/dataset/Chars74k/splitted'
  image_size: 100
  k: 0
  number: True
  upper: False
  lower: False
  good: True
  bad: True
  language: English

trainer:
  max_epochs: 10000
  min_epochs: 10
  gpus: 1
  precision: 32
  fast_dev_run: ${debug}
  profiler: simple
  weights_summary: full
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  distributed_backend: ~

model_checkpoint:
  dirpath: './checkpoints'
  filename: ~
  monitor: metrics/valid_loss
  verbose: False
  save_last: True
  save_top_k: 1
  save_weights_only: False
  mode: min

early_stopping:
  monitor: metrics/valid_loss
  min_delta: 0
  patience: 30
  verbose: False
  mode: min

callbacks: []

loggers:
  - _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: .
    name: 'TensorBoard'
    version: ''

hydra:
  run:
    dir: ./outputs/${experiment_name}/${dataset_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}-single
  sweep:
    dir: ./outputs/${experiment_name}/${dataset_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}-multiple
