project_name: PatchSetsRL
experiment_name: Default

debug: False

hparams:
  done_prob: 0.99
  total_steps_entropy_coef: 1
  start_entropy_coef: 1e-1
  end_entropy_coef: 1e-3

env:
  checkpoint_path: /workspace/src/env_model/epoch=1062.ckpt

agent:
  gpu: 0
  gamma: 0.9
  update_interval: 1024
  minibatch_size: 64

experiment:
  steps: 100_000
  eval_interval: 1024
  eval_n_episodes: 104
  eval_n_steps: ~
  train_max_episode_len: 8
  eval_max_episode_len: 8
  use_tensorboard: True

optim:
  lr: 1e-3
  eps: 1e-8

hydra:
  run:
    dir: ./outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
